### ISSUE TITLE
Build using apiconnect or slc loopback?

### ISSUE THREAD

**Issue by scheung38** [tngan/loopback-redux-react-boilerplate#2]
1. Is it built using apic or slc? Does it matter? Since I see apiconnect folder in project?
2. What about datasource from API ? I have API but not sure how to connect?

**Comment by tngan** [comment]
@scheung38 
1. It is up to you to use either slc or IBM API Connect Developer Toolkit. See [here](http://loopback.io/doc/en/lb2/Installation.html).
2. The datasource is specified in `server/datasources.json`. Check out the documentation [here](https://docs.strongloop.com/display/public/LB/datasources.json).
