### ISSUE TITLE
Question: usage of babel-plugin-react-transform and react-transform-hmr with webpack.HotModuleReplacementPlugin

### ISSUE THREAD

**Issue by benomatis** [tngan/loopback-redux-react-boilerplate#5]
Reading through the README.md of both, babel-plugin-react-transform and react-transform-hmr they claim to be "highly experimental tech" - any reasons you're using this while also having webpack.HotModuleReplacementPlugin enabled?

I'm relatively new to the whole node.js and related tech, so please bear with me if this is a stupid question.

**Comment by tngan** [comment]
This project has started 2 years ago, and I haven't updated this repo for long time, something that might be updated and not essential. In fact, we don't need hot reload in production but it's just worth for development.

**Comment by benomatis** [comment]
What I meant was more that those modules aren't even needed for development, view the presence of webpack doing the same. Is there anything they do specifically or can I just remove them (at least in my own project)? I'm trying to make a super lightweight and actual version of this.

And by the way, thanks so much for this boilerplate, saved me a lot of time doing it from scratch!

**Comment by tngan** [comment]
Yes, if it isn't needed, we can remove them as well. I have done some experiments when I made this boilerplate, so that some packages are included but not required.

I can grant you the access as a repo collaborator and maintainer as well.

**Comment by benomatis** [comment]
I'm still in the experimenting stages, so I wouldn't go as far as getting access as a maintainer, but I appreciate the trust. I'd much rather just go via PR's for now, if that's ok with you; don't want to accidentally create a mess here... Would that be ok with you or are you actually looking for someone to take over, ie. you don't have enough resources or don't care that much anymore about this project...?

**Comment by tngan** [comment]
Feel free to make PRs. I always look for new maintainers and contribute back to the community.

**Comment by benomatis** [comment]
ok, created one for this specifically, let's see how it goes.
